name: run-tests
run-name: ${{ github.actor }} is testing the code
on:
    push:
      branches:
        - 'main'
jobs:
  run-api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - run: rpm run test
